all: consumer.cpp producer.cpp manager.cpp
	g++ consumer.cpp -o consumer
	g++ manager.cpp -o manager
	g++ producer.cpp -o producer

clean:
	rm consumer manager producer result0.txt result1.txt matrix.txt